### ISSUE TITLE
how do you install and use this?

### ISSUE THREAD

**Issue by IPleaseHelpI** [midgen/UnrealFastNoise#6]
Sorry for being a noob. how do i install and use? this thank you!

**Comment by victorbstan** [comment]
git clone into Plugins folder in your Unreal project folder. If "Plugins" doesn't exist, just make it. You have to restart your editor and then check "Edit > Plugins > Project" and enable it there. Although as of this writing it doesn't seem to be compatible with UE 4.17.1

**Comment by midgen** [comment]
@victorbstan instructions are correct.

**Comment by rudedogg** [comment]
Leaving these instructions incase I have to do this again. This is what I do on macOS to get Unreal to compile the plugin:

1. Create a new Unreal Project, I use the Blank template, choose C++ instead of Blueprints.
2. Navigate to the project directory in a file browser or terminal, and add a `Plugins` directory at the top level.
3. Copy this repository to the newly created `Plugins` directory
  If using a terminal/git: 
      - `cd Plugins`
      - `git clone https://github.com/midgen/UnrealFastNoise.git`

   Manually using a file browser:
      - Download the .zip of this repository and copy it into `{Your Project}/Plugins`
3. Go to the Plugins menu in Unreal Editor (Edit -> Plugins) and enable `UnrealFastNoisePlugin`.  If you can't find it, select "Project Plugins" in the left column in the Plugins window. 
**DO NOT RESTART THE EDITOR YET!**
4. In the Unreal Editor -> Content Browser panel, click `Add New`, and select `New C++ Class`.
5. Select any parent, it doesn't matter. We just want Unreal to compile the plugin by creating a new C++ class.
6. If the compile completes without errors, you're good to go! You can now use the plugin in your project, just restart Unreal Editor. If you want to use the plugin in a different project without going through this again, just create a `Plugins` directory and copy the newly compiled plugin directory into the new project .
